### ISSUE TITLE
 ErrorException (E_NOTICE)  Array to string conversion 

### ISSUE THREAD

**Issue by herlon214** [willrowe/laravel-response-cache#1]
Trying to cache a controller:

`Route::controller('/myController', ['myController', 'cache' => 30]);`

Returns:

`Array to string conversion`

Laravel 4.2

**Comment by willrowe** [comment]
Caching through the `controller` method is not supported since there is no way to pass the route action.
The second parameter for the `controller` method must be a string and not an array.
